server:
  port: 8001
spring:
  application:
    name: user-consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka7071.com:7071/eureka/,http://eureka7072.com:7072/eureka
  instance:
    prefer-ip-address: true