server:
  port: 9003
spring:
  application:
    name: user-service-provider
eureka:
  instance:
    hostname: user-service-provider9003
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7071.com:7071/eureka/,http://eureka7072.com:7072/eureka