server:
  port: 7072
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7071.com:7071/eureka/
  instance:
    hostname: eureka7072.com